databases:
  - name: qrconnects
    databaseName: qrconnects
    user: qrconnects
    plan: free

services:
  - type: web
    name: qrconnects
    env: python
    plan: free
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrconnects
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: off
      - key: CORS_ALLOWED_ORIGINS
        value: https://qrconnects.netlify.app